#! /bin/sh
#
# Needed for the libvirt worker to access libvirt from the host
#
# See https://github.com/docker/for-linux/issues/264 for why this is so
# difficult, and for the workaround itself

echo -e "`/sbin/ip route|awk '/default/ { print $3 }'`" > /var/lib/buildbot/host_ip
exec "$@"
