#! /bin/sh -e
# Script that creates the container images we need in the cluster, apart
# from the worker itself

project=$1
buildbot_version=$2
revision=$3
if test -z "$project" || test -z "$buildbot_version" || test -z "$revision"; then
    echo "usage: containers.sh PROJECT BUILDBOT_VERSION REVISION"
    exit 1
fi

echo "Pushing containers for project ${project}"
container_tag=$buildbot_version-$revision
echo "Tag: $container_tag"

docker push gcr.io/$project/cache-apt
docker push gcr.io/$project/cache-gem
docker push gcr.io/$project/volume-nfs
docker push gcr.io/$project/buildbot-master:$container_tag
docker push gcr.io/$project/buildbot-worker-base:$container_tag
docker push gcr.io/$project/buildbot-worker:$container_tag
