#! /bin/bash -e

sudo apt-get update
sudo apt-get install -y omniorb-nameserver omniorb

( nohup setsid /usr/bin/omniNames -start -always -datadir /tmp -errlog /tmp/omniNames-errors.log ) &

while ! /usr/bin/nameclt list; do
    sleep 1
done

